### ISSUE TITLE
Error when building the project 

### ISSUE THREAD

**Issue by daggala** [kristjanmik/kjosturett-web#11]
when I run: **npm run build-data** I get this error:

(async () => {
       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)

**Comment by kristjanmik** [comment]
What is your node version? Node 8.5+ is needed to run this code without transformation. I might add a dump.zip file so people won't get stranded on this issue though

**Comment by daggala** [comment]
Ah yes, I have a Node v6.11.2
